import { Page, Text, View, Document, StyleSheet } from '@react-pdf/renderer';
import { GatePassItem } from '../services/gatePassService';
import { Organization } from '../services/organizationService';

const styles = StyleSheet.create({
  page: {
    padding: 40,
    fontFamily: 'Helvetica',
    fontSize: 10,
    color: '#333',
  },
  header: {
    textAlign: 'center',
    borderBottomWidth: 2,
    borderBottomColor: '#e2e8f0',
    paddingBottom: 15,
    marginBottom: 25,
  },
  title: {
    fontSize: 22,
    fontWeight: 'bold',
    letterSpacing: 2,
    color: '#0f172a',
    textAlign: 'center',
  },
  subtitle: {
    fontSize: 9,
    color: '#64748b',
    marginTop: 4,
    textAlign: 'center',
    textTransform: 'uppercase',
    letterSpacing: 1,
  },
  grid: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 20,
  },
  gridCol: {
    width: '48%',
  },
  divider: {
    borderTopWidth: 1,
    borderTopColor: '#f1f5f9',
    paddingTop: 10,
    marginBottom: 10,
  },
  label: {
    fontSize: 8,
    color: '#64748b',
    fontWeight: 'bold',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
    marginBottom: 2,
  },
  value: {
    fontSize: 11,
    fontWeight: 'bold',
    color: '#1e293b',
  },
  monoValue: {
    fontSize: 11,
    fontWeight: 'bold',
    color: '#2563eb',
    fontFamily: 'Courier',
  },
  signatures: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 60,
    paddingTop: 20,
  },
  sigBox: {
    borderTopWidth: 1.5,
    borderTopColor: '#94a3b8',
    paddingTop: 6,
    width: '40%',
    textAlign: 'center',
    fontSize: 9,
    fontWeight: 'bold',
    color: '#64748b',
    textTransform: 'uppercase',
  },
  footer: {
    position: 'absolute',
    bottom: 40,
    left: 40,
    right: 40,
    textAlign: 'center',
    borderTopWidth: 1,
    borderTopColor: '#eee',
    paddingTop: 10,
    fontSize: 8,
    color: '#999',
  }
});

export const PDFGatePass = ({ gp, org }: { gp: GatePassItem, org: Organization }) => {
  return (
    <Document>
      <Page size="A4" style={styles.page}>
        <View style={styles.header}>
          <Text style={styles.title}>GATE PASS</Text>
          <Text style={styles.subtitle}>{(org && org.name) || 'Shan Dyeing'} — Textile Factory</Text>
        </View>

        <View style={styles.grid}>
          <View style={styles.gridCol}>
            <Text style={styles.label}>Gate Pass No:</Text>
            <Text style={styles.value}>{gp.gate_pass_no}</Text>
          </View>
          <View style={styles.gridCol}>
            <Text style={styles.label}>Date:</Text>
            <Text style={styles.value}>
              {new Date(gp.gate_pass_date).toLocaleDateString('en-PK', { day: '2-digit', month: 'long', year: 'numeric' })}
            </Text>
          </View>
        </View>

        <View style={styles.divider}>
          <Text style={styles.label}>Party Name / Customer:</Text>
          <Text style={styles.value}>{gp.delivery_order?.customer?.name || '—'}</Text>
        </View>

        <View style={styles.divider}>
          <Text style={styles.label}>DO Reference Number:</Text>
          <Text style={styles.monoValue}>{gp.delivery_order?.order_no || '—'}</Text>
        </View>

        <View style={styles.divider}>
          <Text style={styles.label}>Total Gazana:</Text>
          <Text style={styles.value}>
            {gp.delivery_order ? `${Number(gp.delivery_order.total_gray_gazana || 0).toLocaleString()} GZ` : '—'}
          </Text>
        </View>

        <View style={styles.divider}>
          <Text style={styles.label}>Vehicle Number:</Text>
          <Text style={styles.value}>{gp.vehicle_no || '—'}</Text>
        </View>

        <View style={styles.divider}>
          <Text style={styles.label}>Driver Name:</Text>
          <Text style={styles.value}>{gp.driver_name || '—'}</Text>
        </View>

        <View style={styles.divider}>
          <Text style={styles.label}>Driver Mobile:</Text>
          <Text style={styles.value}>{gp.driver_mobile || '—'}</Text>
        </View>

        <View style={styles.divider}>
          <Text style={styles.label}>Additional Notes / Transport Details:</Text>
          <Text style={styles.value}>{gp.notes || '—'}</Text>
        </View>

        <View style={styles.signatures}>
          <View style={styles.sigBox}>
            <Text>Security Signature</Text>
          </View>
          <View style={styles.sigBox}>
            <Text>Authorized Signature</Text>
          </View>
        </View>

        <Text style={styles.footer}>
          This is an official document generated by Shan Dyeing ERP Software.
        </Text>
      </Page>
    </Document>
  );
};
